CREATE OR ALTER VIEW
  tableau.staff_roster AS
SELECT
  df_employee_number,
  adp_associate_id AS associate_id,
  position_id,
  file_number,
  first_name,
  last_name,
  preferred_first_name AS preferred_first,
  preferred_last_name AS preferred_last,
  preferred_name,
  NULL AS maiden_name,
  NULL AS eeo_ethnic_code,
  primary_ethnicity AS eeo_ethnic_description,
  is_hispanic,
  gender,
  birth_date,
  [address],
  city AS primary_address_city,
  [state] AS primary_address_state_territory_code,
  postal_code AS primary_address_zip_postal_code,
  mobile_number AS personal_contact_personal_mobile,
  primary_on_site_department AS subject_dept_custom,
  grades_taught AS grades_taught_custom,
  original_hire_date,
  rehire_date,
  primary_job AS job_title_description,
  primary_job AS job_title_custom,
  payroll_company_code,
  legal_entity_name,
  is_regional_staff,
  [status] AS position_status,
  primary_site AS location_description,
  primary_site AS location_custom,
  primary_on_site_department AS home_department_description,
  status_reason AS termination_reason_description,
  payclass AS worker_category_description,
  job_family AS benefits_eligibility_class_description,
  flsa_status AS flsa_description,
  is_manager AS this_is_a_management_position,
  is_manager AS is_management,
  salesforce_id AS salesforce_job_position_name_custom,
  manager_name AS reports_to_name,
  manager_df_employee_number,
  manager_adp_associate_id AS manager_custom_assoc_id,
  manager_name AS manager_name,
  position_effective_from_date AS position_start_date,
  termination_date,
  LOWER(mail) AS mail,
  LOWER(userprincipalname) AS userprincipalname,
  LOWER(manager_mail) AS manager_mail
FROM
  gabby.people.staff_crosswalk_static
