[project]
name = ""
version = ""
description = ""
authors = [
  { name = "Charlie Bini", email = "5003326+cbini@users.noreply.github.com" },
]
dependencies = ["dbt-sqlserver<1.4", "pip>=23.0.1", "dbt-core<1.5"]
requires-python = ">=3.10"
license = { text = "GPL-3.0-or-later" }
