[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
  { name = "Charlie Bini", email = "5003326+cbini@users.noreply.github.com" },
]
dependencies = ["dbt-sqlserver>=1.3.1", "pip>=23.0.1"]
requires-python = ">=3.10"
license = { text = "GPL-3.0-or-later" }
