USE gabby
GO

CREATE OR ALTER VIEW parcc.summative_record_file AS

SELECT state_student_identifier
      ,local_student_identifier
      ,parccstudent_identifier
      ,first_name
      ,middle_name
      ,last_or_surname
      ,academic_year      
      ,subject
      ,test_code
      ,test_performance_level
      ,test_scale_score      
      ,test_csemprobable_range      
      ,test_reading_scale_score
      ,test_reading_csem
      ,test_writing_scale_score
      ,test_writing_csem
      ,assessment_year
      ,record_type
      ,summative_flag
      ,test_status

      ,state_abbreviation
      ,testing_district_code
      ,testing_school_code
      ,responsible_district_code
      ,responsible_school_code      
      ,birthdate
      ,sex
      ,grade_level_when_assessed
      ,hispanic_or_latino_ethnicity
      ,american_indian_or_alaska_native
      ,asian
      ,black_or_african_american
      ,native_hawaiian_or_other_pacific_islander
      ,white
      ,two_or_more_races
      ,english_learner_el
      ,title_iiilimited_english_proficient_participation_status
      ,giftedand_talented
      ,migrant_status
      ,economic_disadvantage_status
      ,student_with_disabilities
      ,primary_disability_type
      ,state_field_1
      ,state_field_2
      ,state_field_3
      ,state_field_4
      ,state_field_5
      ,state_field_6
      ,state_field_7
      ,state_field_8
      ,state_field_9
      ,state_field_10
      ,class_name
      ,test_administrator
      ,staff_member_identifier      
      ,retest
      ,elaccommodation
      ,frequent_breaks
      ,separate_alternate_location
      ,small_testing_group
      ,specialized_equipment_or_furniture
      ,specified_area_or_setting
      ,time_of_day
      ,answer_masking
      ,assistive_technology_screen_reader
      ,closed_captioning_for_elal
      ,student_reads_assessment_aloud_to_self
      ,human_signer_for_test_directions
      ,calculation_device_and_mathematics_tools
      ,elalconstructed_response
      ,elalselected_response_or_technology_enhanced_items
      ,mathematics_response
      ,monitor_test_response
      ,word_prediction
      ,administration_directions_clarifiedin_students_native_language
      ,administration_directions_read_aloudin_students_native_language
      ,mathematics_response_el
      ,wordto_word_dictionary_english_native_language
      ,emergency_accommodation
      ,extended_time
      ,student_test_uuid
      ,paper_form_id
      ,online_form_id      
      ,total_test_items
      ,test_attemptedness_flag
      ,total_test_items_attempted
      ,paper_attempt_create_date
      ,paper_section_1_total_test_items
      ,paper_section_1_numberof_attempted_items
      ,paper_section_2_total_test_items
      ,paper_section_2_numberof_attempted_items
      ,paper_section_3_total_test_items
      ,paper_section_3_numberof_attempted_items
      ,paper_section_4_total_test_items
      ,paper_section_4_numberof_attempted_items
      ,student_unit_1_test_uuid
      ,unit_1_form_id
      ,unit_1_total_test_items
      ,unit_1_numberof_attempted_items
      ,student_unit_2_test_uuid
      ,unit_2_form_id
      ,unit_2_total_test_items
      ,unit_2_number_of_attempted_items
      ,student_unit_3_test_uuid
      ,unit_3_form_id
      ,unit_3_total_test_items
      ,unit_3_number_of_attempted_items
      ,student_unit_4_test_uuid
      ,unit_4_form_id
      ,unit_4_total_test_items
      ,unit_4_numberof_attempted_items
      ,not_tested_code
      ,not_tested_reason
      ,void_score_code
      ,void_score_reason
      ,ship_report_district_code
      ,ship_report_school_code      
      ,multiple_test_registration
      ,attempt_create_date
      ,unit_1_online_test_start_date_time
      ,unit_1_online_test_end_date_time
      ,unit_2_online_test_start_date_time
      ,unit_2_online_test_end_date_time
      ,unit_3_online_test_start_date_time
      ,unit_3_online_test_end_date_time
      ,unit_4_online_test_start_date_time
      ,unit_4_online_test_end_date_time      
      ,assessment_grade      
      ,federal_race_ethnicity
      ,period
      ,testing_organizational_type
      ,testing_district_name
      ,testing_school_name
      ,responsible_organization_code_type
      ,responsible_organizational_type
      ,responsible_district_name
      ,responsible_school_name      
      ,subclaim_1_category
      ,subclaim_2_category
      ,subclaim_3_category
      ,subclaim_4_category
      ,subclaim_5_category
      ,test_score_complete
      ,word_prediction_for_elal      
      ,assessment_accommodation_english_learner
      ,assessment_accommodation_504
      ,assessment_accommodation_individualized_educational_plan
      ,text_to_speech
      ,text_to_speech_for_mathematics
      ,text_to_speech_for_elal
      ,human_reader_or_human_signer
      ,human_reader_or_human_signer_for_mathematics
      ,human_reader_or_human_signer_for_elal
      ,pba_form_id
      ,pba_not_tested_reason
      ,pba_student_test_uuid
      ,pba_test_attemptedness_flag
      ,pba_testing_district_identifier
      ,pba_testing_district_name
      ,pba_testing_school_institution_identifier
      ,pba_testing_school_institution_name
      ,pba_total_test_items
      ,pba_total_test_items_attempted
      ,pba_unit_1_number_of_attempted_items
      ,pba_unit_1_total_number_of_items
      ,pba_unit_2_number_of_attempted_items
      ,pba_unit_2_total_number_of_items
      ,pba_unit_3_number_of_attempted_items
      ,pba_unit_3_total_number_of_items      
FROM kippnewark.parcc.summative_record_file_clean

UNION ALL

SELECT state_student_identifier
      ,local_student_identifier
      ,parccstudent_identifier
      ,first_name
      ,middle_name
      ,last_or_surname
      ,academic_year      
      ,subject
      ,test_code
      ,test_performance_level
      ,test_scale_score      
      ,test_csemprobable_range      
      ,test_reading_scale_score
      ,test_reading_csem
      ,test_writing_scale_score
      ,test_writing_csem
      ,assessment_year
      ,record_type
      ,summative_flag
      ,test_status

      ,state_abbreviation
      ,testing_district_code
      ,testing_school_code
      ,responsible_district_code
      ,responsible_school_code      
      ,birthdate
      ,sex
      ,grade_level_when_assessed
      ,hispanic_or_latino_ethnicity
      ,american_indian_or_alaska_native
      ,asian
      ,black_or_african_american
      ,native_hawaiian_or_other_pacific_islander
      ,white
      ,two_or_more_races
      ,english_learner_el
      ,title_iiilimited_english_proficient_participation_status
      ,giftedand_talented
      ,migrant_status
      ,economic_disadvantage_status
      ,student_with_disabilities
      ,primary_disability_type
      ,state_field_1
      ,state_field_2
      ,state_field_3
      ,state_field_4
      ,state_field_5
      ,state_field_6
      ,state_field_7
      ,state_field_8
      ,state_field_9
      ,state_field_10
      ,class_name
      ,test_administrator
      ,staff_member_identifier      
      ,retest
      ,elaccommodation
      ,frequent_breaks
      ,separate_alternate_location
      ,small_testing_group
      ,specialized_equipment_or_furniture
      ,specified_area_or_setting
      ,time_of_day
      ,answer_masking
      ,assistive_technology_screen_reader
      ,closed_captioning_for_elal
      ,student_reads_assessment_aloud_to_self
      ,human_signer_for_test_directions
      ,calculation_device_and_mathematics_tools
      ,elalconstructed_response
      ,elalselected_response_or_technology_enhanced_items
      ,mathematics_response
      ,monitor_test_response
      ,word_prediction
      ,administration_directions_clarifiedin_students_native_language
      ,administration_directions_read_aloudin_students_native_language
      ,mathematics_response_el
      ,wordto_word_dictionary_english_native_language
      ,emergency_accommodation
      ,extended_time
      ,student_test_uuid
      ,paper_form_id
      ,online_form_id      
      ,total_test_items
      ,test_attemptedness_flag
      ,total_test_items_attempted
      ,paper_attempt_create_date
      ,paper_section_1_total_test_items
      ,paper_section_1_numberof_attempted_items
      ,paper_section_2_total_test_items
      ,paper_section_2_numberof_attempted_items
      ,paper_section_3_total_test_items
      ,paper_section_3_numberof_attempted_items
      ,paper_section_4_total_test_items
      ,paper_section_4_numberof_attempted_items
      ,student_unit_1_test_uuid
      ,unit_1_form_id
      ,unit_1_total_test_items
      ,unit_1_numberof_attempted_items
      ,student_unit_2_test_uuid
      ,unit_2_form_id
      ,unit_2_total_test_items
      ,unit_2_number_of_attempted_items
      ,student_unit_3_test_uuid
      ,unit_3_form_id
      ,unit_3_total_test_items
      ,unit_3_number_of_attempted_items
      ,student_unit_4_test_uuid
      ,unit_4_form_id
      ,unit_4_total_test_items
      ,unit_4_numberof_attempted_items
      ,not_tested_code
      ,not_tested_reason
      ,void_score_code
      ,void_score_reason
      ,ship_report_district_code
      ,ship_report_school_code      
      ,multiple_test_registration
      ,attempt_create_date
      ,unit_1_online_test_start_date_time
      ,unit_1_online_test_end_date_time
      ,unit_2_online_test_start_date_time
      ,unit_2_online_test_end_date_time
      ,unit_3_online_test_start_date_time
      ,unit_3_online_test_end_date_time
      ,unit_4_online_test_start_date_time
      ,unit_4_online_test_end_date_time      
      ,assessment_grade      
      ,federal_race_ethnicity
      ,period
      ,testing_organizational_type
      ,testing_district_name
      ,testing_school_name
      ,responsible_organization_code_type
      ,responsible_organizational_type
      ,responsible_district_name
      ,responsible_school_name      
      ,subclaim_1_category
      ,subclaim_2_category
      ,subclaim_3_category
      ,subclaim_4_category
      ,subclaim_5_category
      ,test_score_complete
      ,word_prediction_for_elal      
      ,assessment_accommodation_english_learner
      ,assessment_accommodation_504
      ,assessment_accommodation_individualized_educational_plan
      ,text_to_speech
      ,text_to_speech_for_mathematics
      ,text_to_speech_for_elal
      ,human_reader_or_human_signer
      ,human_reader_or_human_signer_for_mathematics
      ,human_reader_or_human_signer_for_elal
      ,pba_form_id
      ,pba_not_tested_reason
      ,pba_student_test_uuid
      ,pba_test_attemptedness_flag
      ,pba_testing_district_identifier
      ,pba_testing_district_name
      ,pba_testing_school_institution_identifier
      ,pba_testing_school_institution_name
      ,pba_total_test_items
      ,pba_total_test_items_attempted
      ,pba_unit_1_number_of_attempted_items
      ,pba_unit_1_total_number_of_items
      ,pba_unit_2_number_of_attempted_items
      ,pba_unit_2_total_number_of_items
      ,pba_unit_3_number_of_attempted_items
      ,pba_unit_3_total_number_of_items      
FROM kippcamden.parcc.summative_record_file_clean