USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.teachercategory AS

SELECT 'kippcamden' AS [db_name]
      ,[categorytype]
      ,[color]
      ,[defaultdaysbeforedue]
      ,[defaultpublishoption]
      ,[defaultscoreentrypoints]
      ,[defaultscoretype]
      ,[defaulttotalvalue]
      ,[defaultweight]
      ,[description]
      ,[displayposition]
      ,[districtteachercategoryid]
      ,[isactive]
      ,[isdefaultpublishscores]
      ,[isinfinalgrades]
      ,[isusermodifiable]
      ,[name]
      ,[teachercategoryid]
      ,[teachermodified]
      ,[usersdcid]
FROM kippcamden.powerschool.teachercategory
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[categorytype]
      ,[color]
      ,[defaultdaysbeforedue]
      ,[defaultpublishoption]
      ,[defaultscoreentrypoints]
      ,[defaultscoretype]
      ,[defaulttotalvalue]
      ,[defaultweight]
      ,[description]
      ,[displayposition]
      ,[districtteachercategoryid]
      ,[isactive]
      ,[isdefaultpublishscores]
      ,[isinfinalgrades]
      ,[isusermodifiable]
      ,[name]
      ,[teachercategoryid]
      ,[teachermodified]
      ,[usersdcid]
FROM kippmiami.powerschool.teachercategory
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[categorytype]
      ,[color]
      ,[defaultdaysbeforedue]
      ,[defaultpublishoption]
      ,[defaultscoreentrypoints]
      ,[defaultscoretype]
      ,[defaulttotalvalue]
      ,[defaultweight]
      ,[description]
      ,[displayposition]
      ,[districtteachercategoryid]
      ,[isactive]
      ,[isdefaultpublishscores]
      ,[isinfinalgrades]
      ,[isusermodifiable]
      ,[name]
      ,[teachercategoryid]
      ,[teachermodified]
      ,[usersdcid]
FROM kippnewark.powerschool.teachercategory;