USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.schoolstaff AS

SELECT 'kippcamden' AS [db_name]
      ,[balance_1]
      ,[balance_2]
      ,[balance_3]
      ,[balance_4]
      ,[dcid]
      ,[id]
      ,[log]
      ,[noofcurclasses]
      ,NULL AS [notes]
      ,[sched_classroom]
      ,[sched_department]
      ,[sched_housecode]
      ,[sched_isteacherfree]
      ,[sched_lunch]
      ,[sched_maximumconsecutive]
      ,[sched_maximumcourses]
      ,[sched_maximumduty]
      ,[sched_maximumfree]
      ,[sched_maxpers]
      ,[sched_maxpreps]
      ,[sched_scheduled]
      ,[sched_substitute]
      ,[sched_teachermoreoneschool]
      ,[sched_totalcourses]
      ,[sched_usebuilding]
      ,[sched_usehouse]
      ,[schoolid]
      ,[staffstatus]
      ,[status]
      ,[users_dcid]
FROM kippcamden.powerschool.schoolstaff
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[balance_1]
      ,[balance_2]
      ,[balance_3]
      ,[balance_4]
      ,[dcid]
      ,[id]
      ,[log]
      ,[noofcurclasses]
      ,NULL AS [notes]
      ,[sched_classroom]
      ,[sched_department]
      ,[sched_housecode]
      ,[sched_isteacherfree]
      ,[sched_lunch]
      ,[sched_maximumconsecutive]
      ,[sched_maximumcourses]
      ,[sched_maximumduty]
      ,[sched_maximumfree]
      ,[sched_maxpers]
      ,[sched_maxpreps]
      ,[sched_scheduled]
      ,[sched_substitute]
      ,[sched_teachermoreoneschool]
      ,[sched_totalcourses]
      ,[sched_usebuilding]
      ,[sched_usehouse]
      ,[schoolid]
      ,[staffstatus]
      ,[status]
      ,[users_dcid]
FROM kippmiami.powerschool.schoolstaff
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[balance_1]
      ,[balance_2]
      ,[balance_3]
      ,[balance_4]
      ,[dcid]
      ,[id]
      ,[log]
      ,[noofcurclasses]
      ,NULL AS [notes]
      ,[sched_classroom]
      ,[sched_department]
      ,[sched_housecode]
      ,[sched_isteacherfree]
      ,[sched_lunch]
      ,[sched_maximumconsecutive]
      ,[sched_maximumcourses]
      ,[sched_maximumduty]
      ,[sched_maximumfree]
      ,[sched_maxpers]
      ,[sched_maxpreps]
      ,[sched_scheduled]
      ,[sched_substitute]
      ,[sched_teachermoreoneschool]
      ,[sched_totalcourses]
      ,[sched_usebuilding]
      ,[sched_usehouse]
      ,[schoolid]
      ,[staffstatus]
      ,[status]
      ,[users_dcid]
FROM kippnewark.powerschool.schoolstaff;