USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.ps_enrollment_all_static AS

SELECT 'kippcamden' AS [db_name]
      ,[studentid]
      ,[schoolid]
      ,[entrydate]
      ,[entrycode]
      ,[exitdate]
      ,[exitcode]
      ,[grade_level]
      ,[programid]
      ,[fteid]
      ,[membershipshare]
      ,[track]
      ,[dflt_att_mode_code]
      ,[dflt_conversion_mode_code]
      ,[yearid]
      ,[att_calccntpresentabsent]
      ,[att_intervalduration]
FROM kippcamden.powerschool.ps_enrollment_all_static
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[studentid]
      ,[schoolid]
      ,[entrydate]
      ,[entrycode]
      ,[exitdate]
      ,[exitcode]
      ,[grade_level]
      ,[programid]
      ,[fteid]
      ,[membershipshare]
      ,[track]
      ,[dflt_att_mode_code]
      ,[dflt_conversion_mode_code]
      ,[yearid]
      ,[att_calccntpresentabsent]
      ,[att_intervalduration]
FROM kippmiami.powerschool.ps_enrollment_all_static
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[studentid]
      ,[schoolid]
      ,[entrydate]
      ,[entrycode]
      ,[exitdate]
      ,[exitcode]
      ,[grade_level]
      ,[programid]
      ,[fteid]
      ,[membershipshare]
      ,[track]
      ,[dflt_att_mode_code]
      ,[dflt_conversion_mode_code]
      ,[yearid]
      ,[att_calccntpresentabsent]
      ,[att_intervalduration]
FROM kippnewark.powerschool.ps_enrollment_all_static;