USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.cohort_identifiers_scaffold AS

SELECT 'kippcamden' AS [db_name]
      ,[academic_year]
      ,[advisor_name]
      ,[date]
      ,[enroll_status]
      ,[entrydate]
      ,[ethnicity]
      ,[exitdate]
      ,[gender]
      ,[grade_level]
      ,[iep_status]
      ,[is_enrolled]
      ,[lastfirst]
      ,[lep_status]
      ,[lunchstatus]
      ,[reporting_schoolid]
      ,[school_level]
      ,[school_name]
      ,[schoolid]
      ,[student_number]
      ,[studentid]
      ,[team]
      ,[term]
FROM kippcamden.powerschool.cohort_identifiers_scaffold
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[academic_year]
      ,[advisor_name]
      ,[date]
      ,[enroll_status]
      ,[entrydate]
      ,[ethnicity]
      ,[exitdate]
      ,[gender]
      ,[grade_level]
      ,[iep_status]
      ,[is_enrolled]
      ,[lastfirst]
      ,[lep_status]
      ,[lunchstatus]
      ,[reporting_schoolid]
      ,[school_level]
      ,[school_name]
      ,[schoolid]
      ,[student_number]
      ,[studentid]
      ,[team]
      ,[term]
FROM kippmiami.powerschool.cohort_identifiers_scaffold
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[academic_year]
      ,[advisor_name]
      ,[date]
      ,[enroll_status]
      ,[entrydate]
      ,[ethnicity]
      ,[exitdate]
      ,[gender]
      ,[grade_level]
      ,[iep_status]
      ,[is_enrolled]
      ,[lastfirst]
      ,[lep_status]
      ,[lunchstatus]
      ,[reporting_schoolid]
      ,[school_level]
      ,[school_name]
      ,[schoolid]
      ,[student_number]
      ,[studentid]
      ,[team]
      ,[term]
FROM kippnewark.powerschool.cohort_identifiers_scaffold;