USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.ps_attendance_daily AS

SELECT 'kippnewark' AS [db_name]
      ,[id]
      ,[studentid]
      ,[schoolid]
      ,[att_date]
      ,[attendance_codeid]
      ,[att_mode_code]
      ,[calendar_dayid]
      ,[programid]
      ,[total_minutes]
      ,[att_code]
      ,[count_for_ada]
      ,[presence_status_cd]
      ,[count_for_adm]
      ,[a]
      ,[b]
      ,[c]
      ,[d]
      ,[e]
      ,[f]
      ,[insession]
      ,[cycle_day_id]
      ,[abbreviation]
FROM kippnewark.powerschool.ps_attendance_daily
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[id]
      ,[studentid]
      ,[schoolid]
      ,[att_date]
      ,[attendance_codeid]
      ,[att_mode_code]
      ,[calendar_dayid]
      ,[programid]
      ,[total_minutes]
      ,[att_code]
      ,[count_for_ada]
      ,[presence_status_cd]
      ,[count_for_adm]
      ,[a]
      ,[b]
      ,[c]
      ,[d]
      ,[e]
      ,[f]
      ,[insession]
      ,[cycle_day_id]
      ,[abbreviation]
FROM kippmiami.powerschool.ps_attendance_daily
UNION ALL
SELECT 'kippcamden' AS [db_name]
      ,[id]
      ,[studentid]
      ,[schoolid]
      ,[att_date]
      ,[attendance_codeid]
      ,[att_mode_code]
      ,[calendar_dayid]
      ,[programid]
      ,[total_minutes]
      ,[att_code]
      ,[count_for_ada]
      ,[presence_status_cd]
      ,[count_for_adm]
      ,[a]
      ,[b]
      ,[c]
      ,[d]
      ,[e]
      ,[f]
      ,[insession]
      ,[cycle_day_id]
      ,[abbreviation]
FROM kippcamden.powerschool.ps_attendance_daily;