USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.cohort_static AS

SELECT 'kippcamden' AS [db_name]
      ,[studentid]
      ,[studentsdcid]
      ,[student_number]
      ,[schoolid]
      ,[grade_level]
      ,[entrydate]
      ,[exitdate]
      ,[entrycode]
      ,[exitcode]
      ,[exitcomment]
      ,[lunchstatus]
      ,[fteid]
      ,[yearid]
      ,[academic_year]
      ,[rn_year]
      ,[rn_school]
      ,[rn_undergrad]
      ,[rn_all]
      ,[prev_grade_level]
      ,[is_retained_year]
      ,[is_retained_ever]
      ,[year_in_network]
      ,[year_in_school]
      ,[entry_schoolid]
      ,[entry_grade_level]
      ,[region]
      ,[cohort]
      ,[boy_status]
      ,[eoy_status]
FROM kippcamden.powerschool.cohort_static
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[studentid]
      ,[studentsdcid]
      ,[student_number]
      ,[schoolid]
      ,[grade_level]
      ,[entrydate]
      ,[exitdate]
      ,[entrycode]
      ,[exitcode]
      ,[exitcomment]
      ,[lunchstatus]
      ,[fteid]
      ,[yearid]
      ,[academic_year]
      ,[rn_year]
      ,[rn_school]
      ,[rn_undergrad]
      ,[rn_all]
      ,[prev_grade_level]
      ,[is_retained_year]
      ,[is_retained_ever]
      ,[year_in_network]
      ,[year_in_school]
      ,[entry_schoolid]
      ,[entry_grade_level]
      ,[region]
      ,[cohort]
      ,[boy_status]
      ,[eoy_status]
FROM kippmiami.powerschool.cohort_static
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[studentid]
      ,[studentsdcid]
      ,[student_number]
      ,[schoolid]
      ,[grade_level]
      ,[entrydate]
      ,[exitdate]
      ,[entrycode]
      ,[exitcode]
      ,[exitcomment]
      ,[lunchstatus]
      ,[fteid]
      ,[yearid]
      ,[academic_year]
      ,[rn_year]
      ,[rn_school]
      ,[rn_undergrad]
      ,[rn_all]
      ,[prev_grade_level]
      ,[is_retained_year]
      ,[is_retained_ever]
      ,[year_in_network]
      ,[year_in_school]
      ,[entry_schoolid]
      ,[entry_grade_level]
      ,[region]
      ,[cohort]
      ,[boy_status]
      ,[eoy_status]
FROM kippnewark.powerschool.cohort_static;