USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.final_grades_static AS

SELECT 'kippcamden' AS [db_name]
      ,[student_number]
      ,[studentid]
      ,[academic_year]
      ,[schoolid]
      ,[grade_level]
      ,[reporting_term]
      ,[term_name]
      ,[is_curterm]
      ,[credittype]
      ,[course_number]
      ,[course_name]
      ,[sectionid]
      ,[teacher_name]
      ,[excludefromgpa]
      ,[gradescaleid]
      ,[credit_hours]
      ,[term_gpa_points]
      ,[term_grade_letter]
      ,[term_grade_percent]
      ,[term_grade_letter_adjusted]
      ,[term_grade_percent_adjusted]
      ,[e1]
      ,[e1_adjusted]
      ,[e2]
      ,[e2_adjusted]
      ,[weighted_grade_total]
      ,[weighted_points_total]
      ,[y1_grade_percent]
      ,[y1_grade_percent_adjusted]
      ,[y1_grade_letter]
      ,[y1_gpa_points]
      ,[y1_gpa_points_unweighted]
      ,[need_90]
      ,[need_80]
      ,[need_70]
      ,[need_65]
FROM kippcamden.powerschool.final_grades_static
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[student_number]
      ,[studentid]
      ,[academic_year]
      ,[schoolid]
      ,[grade_level]
      ,[reporting_term]
      ,[term_name]
      ,[is_curterm]
      ,[credittype]
      ,[course_number]
      ,[course_name]
      ,[sectionid]
      ,[teacher_name]
      ,[excludefromgpa]
      ,[gradescaleid]
      ,[credit_hours]
      ,[term_gpa_points]
      ,[term_grade_letter]
      ,[term_grade_percent]
      ,[term_grade_letter_adjusted]
      ,[term_grade_percent_adjusted]
      ,[e1]
      ,[e1_adjusted]
      ,[e2]
      ,[e2_adjusted]
      ,[weighted_grade_total]
      ,[weighted_points_total]
      ,[y1_grade_percent]
      ,[y1_grade_percent_adjusted]
      ,[y1_grade_letter]
      ,[y1_gpa_points]
      ,[y1_gpa_points_unweighted]
      ,[need_90]
      ,[need_80]
      ,[need_70]
      ,[need_65]
FROM kippmiami.powerschool.final_grades_static
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[student_number]
      ,[studentid]
      ,[academic_year]
      ,[schoolid]
      ,[grade_level]
      ,[reporting_term]
      ,[term_name]
      ,[is_curterm]
      ,[credittype]
      ,[course_number]
      ,[course_name]
      ,[sectionid]
      ,[teacher_name]
      ,[excludefromgpa]
      ,[gradescaleid]
      ,[credit_hours]
      ,[term_gpa_points]
      ,[term_grade_letter]
      ,[term_grade_percent]
      ,[term_grade_letter_adjusted]
      ,[term_grade_percent_adjusted]
      ,[e1]
      ,[e1_adjusted]
      ,[e2]
      ,[e2_adjusted]
      ,[weighted_grade_total]
      ,[weighted_points_total]
      ,[y1_grade_percent]
      ,[y1_grade_percent_adjusted]
      ,[y1_grade_letter]
      ,[y1_gpa_points]
      ,[y1_gpa_points_unweighted]
      ,[need_90]
      ,[need_80]
      ,[need_70]
      ,[need_65]
FROM kippnewark.powerschool.final_grades_static;