USE gabby
GO

CREATE OR ALTER VIEW powerschool.students AS 

SELECT _file
      ,_fivetran_synced
      ,_line
      ,_modified
      ,alert_discipline
      ,alert_disciplineexpires
      ,alert_guardian
      ,alert_medical
      ,alert_other
      ,allowwebaccess
      ,applic_response_recvd_date
      ,applic_submitted_date
      ,balance_1
      ,balance_2
      ,balance_3
      ,balance_4
      ,building
      ,campusid
      ,city
      ,classof
      ,cumulative_gpa
      ,cumulative_pct
      ,dcid
      ,districtentrydate
      ,districtentrygradelevel
      ,districtofresidence
      ,dob
      ,doctor_name
      ,doctor_phone
      ,emerg_contact_1
      ,emerg_contact_2
      ,emerg_phone_1
      ,emerg_phone_2
      ,enroll_status
      ,enrollment_schoolid
      ,enrollmentcode
      ,enrollmentid
      ,enrollmenttype
      ,entrycode
      ,entrydate
      ,ethnicity
      ,exclude_fr_rank
      ,exitcode
      ,exitcomment
      ,exitdate
      ,family_ident
      ,father
      ,father_studentcont_guid
      ,fedethnicity
      ,fedracedecline
      ,fee_exemption_status
      ,first_name
      ,fteid
      ,fulltimeequiv_obsolete
      ,gender
      ,geocode
      ,gpentryyear
      ,grade_level
      ,gradreqsetid
      ,graduated_rank
      ,graduated_schoolid
      ,graduated_schoolname
      ,guardian_studentcont_guid
      ,guardianemail
      ,home_phone
      ,home_room
      ,house
      ,id
      ,last_name
      ,lastfirst
      ,ldapenabled
      ,locker_combination
      ,locker_number
      ,log
      ,lunch_id
      ,lunchstatus
      ,mailing_city
      ,mailing_geocode
      ,mailing_state
      ,mailing_street
      ,mailing_zip
      ,membershipshare
      ,middle_name
      ,mother
      ,mother_studentcont_guid
      ,next_school
      ,person_id
      ,phone_id
      ,photoflag
      ,sched_loadlock
      ,sched_lockstudentschedule
      ,sched_nextyeargrade
      ,sched_priority
      ,sched_scheduled
      ,sched_yearofgraduation
      ,schoolentrydate
      ,schoolentrygradelevel
      ,schoolid
      ,sdatarn
      ,simple_gpa
      ,simple_pct
      ,ssn
      ,state
      ,state_enrollflag
      ,state_excludefromreporting
      ,state_studentnumber
      ,street
      ,student_allowwebaccess
      ,student_number
      ,student_web_id
      ,student_web_password
      ,studentpers_guid
      ,studentpict_guid
      ,studentschlenrl_guid
      ,summerschoolid
      ,summerschoolnote
      ,teachergroupid
      ,team
      ,track
      ,transfercomment
      ,tuitionpayer
      ,web_id
      ,web_password
      ,wm_createtime
      ,wm_tier
      ,zip
FROM kippnewark.powerschool.students

UNION ALL

SELECT _file
      ,_fivetran_synced
      ,_line
      ,_modified
      ,alert_discipline
      ,alert_disciplineexpires
      ,alert_guardian
      ,alert_medical
      ,alert_other
      ,allowwebaccess
      ,applic_response_recvd_date
      ,applic_submitted_date
      ,balance_1
      ,balance_2
      ,balance_3
      ,balance_4
      ,building
      ,campusid
      ,city
      ,classof
      ,cumulative_gpa
      ,cumulative_pct
      ,dcid
      ,districtentrydate
      ,districtentrygradelevel
      ,districtofresidence
      ,dob
      ,doctor_name
      ,doctor_phone
      ,emerg_contact_1
      ,emerg_contact_2
      ,emerg_phone_1
      ,emerg_phone_2
      ,enroll_status
      ,enrollment_schoolid
      ,enrollmentcode
      ,enrollmentid
      ,enrollmenttype
      ,entrycode
      ,entrydate
      ,ethnicity
      ,exclude_fr_rank
      ,exitcode
      ,exitcomment
      ,exitdate
      ,family_ident
      ,father
      ,father_studentcont_guid
      ,fedethnicity
      ,fedracedecline
      ,fee_exemption_status
      ,first_name
      ,fteid
      ,fulltimeequiv_obsolete
      ,gender
      ,geocode
      ,gpentryyear
      ,grade_level
      ,gradreqsetid
      ,graduated_rank
      ,graduated_schoolid
      ,graduated_schoolname
      ,guardian_studentcont_guid
      ,guardianemail
      ,home_phone
      ,home_room
      ,house
      ,id
      ,last_name
      ,lastfirst
      ,ldapenabled
      ,locker_combination
      ,locker_number
      ,log
      ,lunch_id
      ,lunchstatus
      ,mailing_city
      ,mailing_geocode
      ,mailing_state
      ,mailing_street
      ,mailing_zip
      ,membershipshare
      ,middle_name
      ,mother
      ,mother_studentcont_guid
      ,next_school
      ,person_id
      ,phone_id
      ,photoflag
      ,sched_loadlock
      ,sched_lockstudentschedule
      ,sched_nextyeargrade
      ,sched_priority
      ,sched_scheduled
      ,sched_yearofgraduation
      ,schoolentrydate
      ,schoolentrygradelevel
      ,schoolid
      ,sdatarn
      ,simple_gpa
      ,simple_pct
      ,ssn
      ,state
      ,state_enrollflag
      ,state_excludefromreporting
      ,state_studentnumber
      ,street
      ,student_allowwebaccess
      ,student_number
      ,student_web_id
      ,student_web_password
      ,studentpers_guid
      ,studentpict_guid
      ,studentschlenrl_guid
      ,summerschoolid
      ,summerschoolnote
      ,teachergroupid
      ,team
      ,track
      ,transfercomment
      ,tuitionpayer
      ,web_id
      ,web_password
      ,wm_createtime
      ,wm_tier
      ,zip
FROM kippcamden.powerschool.students

UNION ALL

SELECT _file
      ,_fivetran_synced
      ,_line
      ,_modified
      ,alert_discipline
      ,alert_disciplineexpires
      ,alert_guardian
      ,alert_medical
      ,alert_other
      ,allowwebaccess
      ,applic_response_recvd_date
      ,applic_submitted_date
      ,balance_1
      ,balance_2
      ,balance_3
      ,balance_4
      ,building
      ,campusid
      ,city
      ,classof
      ,cumulative_gpa
      ,cumulative_pct
      ,dcid
      ,districtentrydate
      ,districtentrygradelevel
      ,districtofresidence
      ,dob
      ,doctor_name
      ,doctor_phone
      ,emerg_contact_1
      ,emerg_contact_2
      ,emerg_phone_1
      ,emerg_phone_2
      ,enroll_status
      ,enrollment_schoolid
      ,enrollmentcode
      ,enrollmentid
      ,enrollmenttype
      ,entrycode
      ,entrydate
      ,ethnicity
      ,exclude_fr_rank
      ,exitcode
      ,exitcomment
      ,exitdate
      ,family_ident
      ,father
      ,father_studentcont_guid
      ,fedethnicity
      ,fedracedecline
      ,fee_exemption_status
      ,first_name
      ,fteid
      ,fulltimeequiv_obsolete
      ,gender
      ,geocode
      ,gpentryyear
      ,grade_level
      ,gradreqsetid
      ,graduated_rank
      ,graduated_schoolid
      ,graduated_schoolname
      ,guardian_studentcont_guid
      ,guardianemail
      ,home_phone
      ,home_room
      ,house
      ,id
      ,last_name
      ,lastfirst
      ,ldapenabled
      ,locker_combination
      ,locker_number
      ,log
      ,lunch_id
      ,lunchstatus
      ,mailing_city
      ,mailing_geocode
      ,mailing_state
      ,mailing_street
      ,mailing_zip
      ,membershipshare
      ,middle_name
      ,mother
      ,mother_studentcont_guid
      ,next_school
      ,person_id
      ,phone_id
      ,photoflag
      ,sched_loadlock
      ,sched_lockstudentschedule
      ,sched_nextyeargrade
      ,sched_priority
      ,sched_scheduled
      ,sched_yearofgraduation
      ,schoolentrydate
      ,schoolentrygradelevel
      ,schoolid
      ,sdatarn
      ,simple_gpa
      ,simple_pct
      ,ssn
      ,state
      ,state_enrollflag
      ,state_excludefromreporting
      ,state_studentnumber
      ,street
      ,student_allowwebaccess
      ,student_number
      ,student_web_id
      ,student_web_password
      ,studentpers_guid
      ,studentpict_guid
      ,studentschlenrl_guid
      ,summerschoolid
      ,summerschoolnote
      ,teachergroupid
      ,team
      ,track
      ,transfercomment
      ,tuitionpayer
      ,web_id
      ,web_password
      ,wm_createtime
      ,wm_tier
      ,zip
FROM kippmiami.powerschool.students