USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.gradescaleitem AS

SELECT 'kippcamden' AS [db_name]
      ,[addedvalue]
      ,[alt_grade_points]
      ,[color]
      ,[colorlevels]
      ,[conversiontonumeric]
      ,[countsingpa]
      ,[cutoffpercentage]
      ,[cutoffpoints]
      ,[dcid]
      ,[description]
      ,[displayposition]
      ,[excludefromafg]
      ,[grade_points]
      ,[grade_replacement_policy]
      ,[gradescaleid]
      ,[gradescaletype]
      ,[graduationcredit]
      ,[hasrelatedscales]
      ,[hasspecialgrades]
      ,[id]
      ,[isforcoursegrade]
      ,[isforstandards]
      ,[isgpashown]
      ,[isproficient]
      ,[isscorecodeonassignments]
      ,[istermweightingshown]
      ,[modify_code]
      ,[name]
      ,[numericcutoff]
      ,[numericextras]
      ,[numericmax]
      ,[numericmin]
      ,[numericvalue]
      ,[specialgradescaledcid]
      ,[teacherscale]
      ,[value]
FROM kippcamden.powerschool.gradescaleitem
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[addedvalue]
      ,[alt_grade_points]
      ,[color]
      ,[colorlevels]
      ,[conversiontonumeric]
      ,[countsingpa]
      ,[cutoffpercentage]
      ,[cutoffpoints]
      ,[dcid]
      ,[description]
      ,[displayposition]
      ,[excludefromafg]
      ,[grade_points]
      ,[grade_replacement_policy]
      ,[gradescaleid]
      ,[gradescaletype]
      ,[graduationcredit]
      ,[hasrelatedscales]
      ,[hasspecialgrades]
      ,[id]
      ,[isforcoursegrade]
      ,[isforstandards]
      ,[isgpashown]
      ,[isproficient]
      ,[isscorecodeonassignments]
      ,[istermweightingshown]
      ,[modify_code]
      ,[name]
      ,[numericcutoff]
      ,[numericextras]
      ,[numericmax]
      ,[numericmin]
      ,[numericvalue]
      ,[specialgradescaledcid]
      ,[teacherscale]
      ,[value]
FROM kippmiami.powerschool.gradescaleitem
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[addedvalue]
      ,[alt_grade_points]
      ,[color]
      ,[colorlevels]
      ,[conversiontonumeric]
      ,[countsingpa]
      ,[cutoffpercentage]
      ,[cutoffpoints]
      ,[dcid]
      ,[description]
      ,[displayposition]
      ,[excludefromafg]
      ,[grade_points]
      ,[grade_replacement_policy]
      ,[gradescaleid]
      ,[gradescaletype]
      ,[graduationcredit]
      ,[hasrelatedscales]
      ,[hasspecialgrades]
      ,[id]
      ,[isforcoursegrade]
      ,[isforstandards]
      ,[isgpashown]
      ,[isproficient]
      ,[isscorecodeonassignments]
      ,[istermweightingshown]
      ,[modify_code]
      ,[name]
      ,[numericcutoff]
      ,[numericextras]
      ,[numericmax]
      ,[numericmin]
      ,[numericvalue]
      ,[specialgradescaledcid]
      ,[teacherscale]
      ,[value]
FROM kippnewark.powerschool.gradescaleitem;