USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.termbins AS

SELECT 'kippcamden' AS [db_name]
      ,[collect]
      ,[creditpct]
      ,[currentgrade]
      ,[date_1]
      ,[date_2]
      ,[dcid]
      ,[gradescaleid]
      ,[id]
      ,[numattpoints]
      ,[schoolid]
      ,[showonspreadsht]
      ,[storecode]
      ,[storegrades]
      ,[suppressltrgrd]
      ,[suppresspercentscr]
      ,[termid]
      ,[yearid]
FROM kippcamden.powerschool.termbins
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[collect]
      ,[creditpct]
      ,[currentgrade]
      ,[date_1]
      ,[date_2]
      ,[dcid]
      ,[gradescaleid]
      ,[id]
      ,[numattpoints]
      ,[schoolid]
      ,[showonspreadsht]
      ,[storecode]
      ,[storegrades]
      ,[suppressltrgrd]
      ,[suppresspercentscr]
      ,[termid]
      ,[yearid]
FROM kippmiami.powerschool.termbins
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[collect]
      ,[creditpct]
      ,[currentgrade]
      ,[date_1]
      ,[date_2]
      ,[dcid]
      ,[gradescaleid]
      ,[id]
      ,[numattpoints]
      ,[schoolid]
      ,[showonspreadsht]
      ,[storecode]
      ,[storegrades]
      ,[suppressltrgrd]
      ,[suppresspercentscr]
      ,[termid]
      ,[yearid]
FROM kippnewark.powerschool.termbins;