USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.cc AS

SELECT 'kippcamden' AS [db_name]
      ,[abs_sectionid]
      ,[academic_year]
      ,[attendance_type_code]
      ,[course_number]
      ,[course_number_clean]
      ,[currentabsences]
      ,[currenttardies]
      ,[dateenrolled]
      ,[dateleft]
      ,[dcid]
      ,[expression]
      ,[id]
      ,[lastattmod]
      ,NULL AS [lastgradeupdate]
      ,[log]
      ,[origsectionid]
      ,[schoolid]
      ,[section_number]
      ,[sectionid]
      ,[studentid]
      ,[studyear]
      ,NULL AS [teachercomment]
      ,[teacherid]
      ,[termid]
      ,[unused_2]
      ,[unused_3]
      ,[yearid]
FROM kippcamden.powerschool.cc
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[abs_sectionid]
      ,[academic_year]
      ,[attendance_type_code]
      ,[course_number]
      ,[course_number_clean]
      ,[currentabsences]
      ,[currenttardies]
      ,[dateenrolled]
      ,[dateleft]
      ,[dcid]
      ,[expression]
      ,[id]
      ,[lastattmod]
      ,NULL AS [lastgradeupdate]
      ,[log]
      ,[origsectionid]
      ,[schoolid]
      ,[section_number]
      ,[sectionid]
      ,[studentid]
      ,[studyear]
      ,NULL AS [teachercomment]
      ,[teacherid]
      ,[termid]
      ,[unused_2]
      ,[unused_3]
      ,[yearid]
FROM kippmiami.powerschool.cc
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[abs_sectionid]
      ,[academic_year]
      ,[attendance_type_code]
      ,[course_number]
      ,[course_number_clean]
      ,[currentabsences]
      ,[currenttardies]
      ,[dateenrolled]
      ,[dateleft]
      ,[dcid]
      ,[expression]
      ,[id]
      ,[lastattmod]
      ,NULL AS [lastgradeupdate]
      ,[log]
      ,[origsectionid]
      ,[schoolid]
      ,[section_number]
      ,[sectionid]
      ,[studentid]
      ,[studyear]
      ,NULL AS [teachercomment]
      ,[teacherid]
      ,[termid]
      ,[unused_2]
      ,[unused_3]
      ,[yearid]
FROM kippnewark.powerschool.cc;