USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.gpa_detail AS

SELECT 'kippnewark' AS [db_name]
      ,[academic_year]
      ,[gpa_points_total_semester]
      ,[gpa_points_total_term]
      ,[gpa_points_total_y1]
      ,[gpa_semester]
      ,[gpa_term]
      ,[gpa_y1]
      ,[gpa_y1_unweighted]
      ,[grade_avg_semester]
      ,[grade_avg_term]
      ,[grade_avg_y1]
      ,[grade_level]
      ,[is_curterm]
      ,[n_failing_y1]
      ,[reporting_term]
      ,[schoolid]
      ,[semester]
      ,[student_number]
      ,[term_name]
      ,[total_credit_hours]
      ,[total_credit_hours_semester]
      ,[weighted_gpa_points_semester]
      ,[weighted_gpa_points_term]
      ,[weighted_gpa_points_y1]
FROM kippnewark.powerschool.gpa_detail
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[academic_year]
      ,[gpa_points_total_semester]
      ,[gpa_points_total_term]
      ,[gpa_points_total_y1]
      ,[gpa_semester]
      ,[gpa_term]
      ,[gpa_y1]
      ,[gpa_y1_unweighted]
      ,[grade_avg_semester]
      ,[grade_avg_term]
      ,[grade_avg_y1]
      ,[grade_level]
      ,[is_curterm]
      ,[n_failing_y1]
      ,[reporting_term]
      ,[schoolid]
      ,[semester]
      ,[student_number]
      ,[term_name]
      ,[total_credit_hours]
      ,[total_credit_hours_semester]
      ,[weighted_gpa_points_semester]
      ,[weighted_gpa_points_term]
      ,[weighted_gpa_points_y1]
FROM kippmiami.powerschool.gpa_detail
UNION ALL
SELECT 'kippcamden' AS [db_name]
      ,[academic_year]
      ,[gpa_points_total_semester]
      ,[gpa_points_total_term]
      ,[gpa_points_total_y1]
      ,[gpa_semester]
      ,[gpa_term]
      ,[gpa_y1]
      ,[gpa_y1_unweighted]
      ,[grade_avg_semester]
      ,[grade_avg_term]
      ,[grade_avg_y1]
      ,[grade_level]
      ,[is_curterm]
      ,[n_failing_y1]
      ,[reporting_term]
      ,[schoolid]
      ,[semester]
      ,[student_number]
      ,[term_name]
      ,[total_credit_hours]
      ,[total_credit_hours_semester]
      ,[weighted_gpa_points_semester]
      ,[weighted_gpa_points_term]
      ,[weighted_gpa_points_y1]
FROM kippcamden.powerschool.gpa_detail;