USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.assignmentscore AS

SELECT 'kippcamden' AS [db_name]
      ,[actualscoreentered]
      ,[actualscoregradescaledcid]
      ,[actualscorekind]
      ,[assignmentscoreid]
      ,[assignmentsectionid]
      ,[isabsent]
      ,[iscollected]
      ,[isexempt]
      ,[isincomplete]
      ,[islate]
      ,[ismissing]
      ,[scoreentrydate]
      ,[scorelettergrade]
      ,[scorepercent]
      ,[scorepoints]
      ,[studentsdcid]
FROM kippcamden.powerschool.assignmentscore
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[actualscoreentered]
      ,[actualscoregradescaledcid]
      ,[actualscorekind]
      ,[assignmentscoreid]
      ,[assignmentsectionid]
      ,[isabsent]
      ,[iscollected]
      ,[isexempt]
      ,[isincomplete]
      ,[islate]
      ,[ismissing]
      ,[scoreentrydate]
      ,[scorelettergrade]
      ,[scorepercent]
      ,[scorepoints]
      ,[studentsdcid]
FROM kippmiami.powerschool.assignmentscore
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[actualscoreentered]
      ,[actualscoregradescaledcid]
      ,[actualscorekind]
      ,[assignmentscoreid]
      ,[assignmentsectionid]
      ,[isabsent]
      ,[iscollected]
      ,[isexempt]
      ,[isincomplete]
      ,[islate]
      ,[ismissing]
      ,[scoreentrydate]
      ,[scorelettergrade]
      ,[scorepercent]
      ,[scorepoints]
      ,[studentsdcid]
FROM kippnewark.powerschool.assignmentscore;