USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.attendance_counts_static AS

SELECT 'kippcamden' AS [db_name]
      ,[studentid]
      ,[academic_year]
      ,[reporting_term]
      ,[term_name]
      ,[is_curterm]
      ,[a_count_term]
      ,[a_count_y1]
      ,[ad_count_term]
      ,[ad_count_y1]
      ,[ae_count_term]
      ,[ae_count_y1]
      ,[iss_count_term]
      ,[iss_count_y1]
      ,[oss_count_term]
      ,[oss_count_y1]
      ,[t_count_term]
      ,[t_count_y1]
      ,[t10_count_term]
      ,[t10_count_y1]
      ,[mem_count_term]
      ,[mem_count_y1]
      ,[abs_unexcused_count_y1]
      ,[abs_unexcused_count_term]
      ,[tdy_all_count_y1]
      ,[tdy_all_count_term]
FROM kippcamden.powerschool.attendance_counts_static
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[studentid]
      ,[academic_year]
      ,[reporting_term]
      ,[term_name]
      ,[is_curterm]
      ,[a_count_term]
      ,[a_count_y1]
      ,[ad_count_term]
      ,[ad_count_y1]
      ,[ae_count_term]
      ,[ae_count_y1]
      ,[iss_count_term]
      ,[iss_count_y1]
      ,[oss_count_term]
      ,[oss_count_y1]
      ,[t_count_term]
      ,[t_count_y1]
      ,[t10_count_term]
      ,[t10_count_y1]
      ,[mem_count_term]
      ,[mem_count_y1]
      ,[abs_unexcused_count_y1]
      ,[abs_unexcused_count_term]
      ,[tdy_all_count_y1]
      ,[tdy_all_count_term]
FROM kippmiami.powerschool.attendance_counts_static
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[studentid]
      ,[academic_year]
      ,[reporting_term]
      ,[term_name]
      ,[is_curterm]
      ,[a_count_term]
      ,[a_count_y1]
      ,[ad_count_term]
      ,[ad_count_y1]
      ,[ae_count_term]
      ,[ae_count_y1]
      ,[iss_count_term]
      ,[iss_count_y1]
      ,[oss_count_term]
      ,[oss_count_y1]
      ,[t_count_term]
      ,[t_count_y1]
      ,[t10_count_term]
      ,[t10_count_y1]
      ,[mem_count_term]
      ,[mem_count_y1]
      ,[abs_unexcused_count_y1]
      ,[abs_unexcused_count_term]
      ,[tdy_all_count_y1]
      ,[tdy_all_count_term]
FROM kippnewark.powerschool.attendance_counts_static;