USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.terms AS

SELECT 'kippcamden' AS [db_name]
      ,[abbreviation]
      ,[attendance_calculation_code]
      ,[days_per_cycle]
      ,[dcid]
      ,[firstday]
      ,[id]
      ,[importmap]
      ,[isyearrec]
      ,[lastday]
      ,[name]
      ,[noofdays]
      ,[periods_per_day]
      ,[portion]
      ,[schoolid]
      ,[sterms]
      ,[terminfo_guid]
      ,[termsinyear]
      ,[yearid]
      ,[yearlycredithrs]
FROM kippcamden.powerschool.terms
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[abbreviation]
      ,[attendance_calculation_code]
      ,[days_per_cycle]
      ,[dcid]
      ,[firstday]
      ,[id]
      ,[importmap]
      ,[isyearrec]
      ,[lastday]
      ,[name]
      ,[noofdays]
      ,[periods_per_day]
      ,[portion]
      ,[schoolid]
      ,[sterms]
      ,[terminfo_guid]
      ,[termsinyear]
      ,[yearid]
      ,[yearlycredithrs]
FROM kippmiami.powerschool.terms
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[abbreviation]
      ,[attendance_calculation_code]
      ,[days_per_cycle]
      ,[dcid]
      ,[firstday]
      ,[id]
      ,[importmap]
      ,[isyearrec]
      ,[lastday]
      ,[name]
      ,[noofdays]
      ,[periods_per_day]
      ,[portion]
      ,[schoolid]
      ,[sterms]
      ,[terminfo_guid]
      ,[termsinyear]
      ,[yearid]
      ,[yearlycredithrs]
FROM kippnewark.powerschool.terms;