USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.ps_membership_reg AS

SELECT 'kippnewark' AS [db_name]
      ,[studentid]
      ,[schoolid]
      ,[student_track]
      ,[fteid]
      ,[dflt_att_mode_code]
      ,[dflt_conversion_mode_code]
      ,[att_calccntpresentabsent]
      ,[att_intervalduration]
      ,[grade_level]
      ,[yearid]
      ,[calendardate]
      ,[a]
      ,[b]
      ,[c]
      ,[d]
      ,[e]
      ,[f]
      ,[bell_schedule_id]
      ,[cycle_day_id]
      ,[attendance_conversion_id]
      ,[studentmembership]
      ,[calendarmembership]
      ,[ontrack]
      ,[offtrack]
FROM kippnewark.powerschool.ps_membership_reg
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[studentid]
      ,[schoolid]
      ,[student_track]
      ,[fteid]
      ,[dflt_att_mode_code]
      ,[dflt_conversion_mode_code]
      ,[att_calccntpresentabsent]
      ,[att_intervalduration]
      ,[grade_level]
      ,[yearid]
      ,[calendardate]
      ,[a]
      ,[b]
      ,[c]
      ,[d]
      ,[e]
      ,[f]
      ,[bell_schedule_id]
      ,[cycle_day_id]
      ,[attendance_conversion_id]
      ,[studentmembership]
      ,[calendarmembership]
      ,[ontrack]
      ,[offtrack]
FROM kippmiami.powerschool.ps_membership_reg
UNION ALL
SELECT 'kippcamden' AS [db_name]
      ,[studentid]
      ,[schoolid]
      ,[student_track]
      ,[fteid]
      ,[dflt_att_mode_code]
      ,[dflt_conversion_mode_code]
      ,[att_calccntpresentabsent]
      ,[att_intervalduration]
      ,[grade_level]
      ,[yearid]
      ,[calendardate]
      ,[a]
      ,[b]
      ,[c]
      ,[d]
      ,[e]
      ,[f]
      ,[bell_schedule_id]
      ,[cycle_day_id]
      ,[attendance_conversion_id]
      ,[studentmembership]
      ,[calendarmembership]
      ,[ontrack]
      ,[offtrack]
FROM kippcamden.powerschool.ps_membership_reg;