USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.attendance AS

SELECT 'kippcamden' AS [db_name]
      ,[ada_value_code]
      ,[ada_value_time]
      ,[adm_value]
      ,[att_comment]
      ,[att_date]
      ,[att_flags]
      ,[att_interval]
      ,[att_mode_code]
      ,[attendance_codeid]
      ,[calendar_dayid]
      ,[ccid]
      ,[dcid]
      ,[id]
      ,[ip_address]
      ,[lock_reporting_yn]
      ,[lock_teacher_yn]
      ,[parent_attendanceid]
      ,[periodid]
      ,[programid]
      ,[schoolid]
      ,[studentid]
      ,[total_minutes]
      ,[whomodifiedid]
      ,[whomodifiedtype]
      ,[yearid]
FROM kippcamden.powerschool.attendance
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[ada_value_code]
      ,[ada_value_time]
      ,[adm_value]
      ,[att_comment]
      ,[att_date]
      ,[att_flags]
      ,[att_interval]
      ,[att_mode_code]
      ,[attendance_codeid]
      ,[calendar_dayid]
      ,[ccid]
      ,[dcid]
      ,[id]
      ,[ip_address]
      ,[lock_reporting_yn]
      ,[lock_teacher_yn]
      ,[parent_attendanceid]
      ,[periodid]
      ,[programid]
      ,[schoolid]
      ,[studentid]
      ,[total_minutes]
      ,[whomodifiedid]
      ,[whomodifiedtype]
      ,[yearid]
FROM kippmiami.powerschool.attendance
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[ada_value_code]
      ,[ada_value_time]
      ,[adm_value]
      ,[att_comment]
      ,[att_date]
      ,[att_flags]
      ,[att_interval]
      ,[att_mode_code]
      ,[attendance_codeid]
      ,[calendar_dayid]
      ,[ccid]
      ,[dcid]
      ,[id]
      ,[ip_address]
      ,[lock_reporting_yn]
      ,[lock_teacher_yn]
      ,[parent_attendanceid]
      ,[periodid]
      ,[programid]
      ,[schoolid]
      ,[studentid]
      ,[total_minutes]
      ,[whomodifiedid]
      ,[whomodifiedtype]
      ,[yearid]
FROM kippnewark.powerschool.attendance;