USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.reenrollments AS

SELECT 'kippcamden' AS [db_name]
      ,[dcid]
      ,[districtofresidence]
      ,[enrollmentcode]
      ,[enrollmenttype]
      ,[entrycode]
      ,[entrycomment]
      ,[entrydate]
      ,[exitcode]
      ,[exitcomment]
      ,[exitdate]
      ,[fteid]
      ,[fulltimeequiv_obsolete]
      ,[grade_level]
      ,[id]
      ,[lunchstatus]
      ,[membershipshare]
      ,[schoolid]
      ,[studentid]
      ,[studentschlenrl_guid]
      ,[track]
      ,[tuitionpayer]
      ,[type]
FROM kippcamden.powerschool.reenrollments
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[dcid]
      ,[districtofresidence]
      ,[enrollmentcode]
      ,[enrollmenttype]
      ,[entrycode]
      ,[entrycomment]
      ,[entrydate]
      ,[exitcode]
      ,[exitcomment]
      ,[exitdate]
      ,[fteid]
      ,[fulltimeequiv_obsolete]
      ,[grade_level]
      ,[id]
      ,[lunchstatus]
      ,[membershipshare]
      ,[schoolid]
      ,[studentid]
      ,[studentschlenrl_guid]
      ,[track]
      ,[tuitionpayer]
      ,[type]
FROM kippmiami.powerschool.reenrollments
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[dcid]
      ,[districtofresidence]
      ,[enrollmentcode]
      ,[enrollmenttype]
      ,[entrycode]
      ,[entrycomment]
      ,[entrydate]
      ,[exitcode]
      ,[exitcomment]
      ,[exitdate]
      ,[fteid]
      ,[fulltimeequiv_obsolete]
      ,[grade_level]
      ,[id]
      ,[lunchstatus]
      ,[membershipshare]
      ,[schoolid]
      ,[studentid]
      ,[studentschlenrl_guid]
      ,[track]
      ,[tuitionpayer]
      ,[type]
FROM kippnewark.powerschool.reenrollments;