USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.ps_attendance_meeting AS

SELECT 'kippcamden' AS [db_name]
      ,[a]
      ,[abbreviation]
      ,[att_code]
      ,[att_date]
      ,[att_interval]
      ,[att_mode_code]
      ,[attendance_codeid]
      ,[b]
      ,[c]
      ,[calculate_ada_yn]
      ,[calendar_dayid]
      ,[cc_schoolid]
      ,[ccid]
      ,[course_credit_points]
      ,[cycle_day_id]
      ,[d]
      ,[dropped]
      ,[e]
      ,[f]
      ,[id]
      ,[insession]
      ,[period_abbreviation]
      ,[period_number]
      ,[periodid]
      ,[presence_status_cd]
      ,[programid]
      ,[schoolid]
      ,[section_number]
      ,[sectionid]
      ,[studentid]
      ,[total_minutes]
FROM kippcamden.powerschool.ps_attendance_meeting
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[a]
      ,[abbreviation]
      ,[att_code]
      ,[att_date]
      ,[att_interval]
      ,[att_mode_code]
      ,[attendance_codeid]
      ,[b]
      ,[c]
      ,[calculate_ada_yn]
      ,[calendar_dayid]
      ,[cc_schoolid]
      ,[ccid]
      ,[course_credit_points]
      ,[cycle_day_id]
      ,[d]
      ,[dropped]
      ,[e]
      ,[f]
      ,[id]
      ,[insession]
      ,[period_abbreviation]
      ,[period_number]
      ,[periodid]
      ,[presence_status_cd]
      ,[programid]
      ,[schoolid]
      ,[section_number]
      ,[sectionid]
      ,[studentid]
      ,[total_minutes]
FROM kippmiami.powerschool.ps_attendance_meeting
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[a]
      ,[abbreviation]
      ,[att_code]
      ,[att_date]
      ,[att_interval]
      ,[att_mode_code]
      ,[attendance_codeid]
      ,[b]
      ,[c]
      ,[calculate_ada_yn]
      ,[calendar_dayid]
      ,[cc_schoolid]
      ,[ccid]
      ,[course_credit_points]
      ,[cycle_day_id]
      ,[d]
      ,[dropped]
      ,[e]
      ,[f]
      ,[id]
      ,[insession]
      ,[period_abbreviation]
      ,[period_number]
      ,[periodid]
      ,[presence_status_cd]
      ,[programid]
      ,[schoolid]
      ,[section_number]
      ,[sectionid]
      ,[studentid]
      ,[total_minutes]
FROM kippnewark.powerschool.ps_attendance_meeting;