USE gabby
GO

ALTER VIEW powerschool.teachers WITH SCHEMABINDING AS

SELECT s.dcid
      ,s.id
      ,u.lastfirst
      ,u.first_name
      ,u.middle_name
      ,u.last_name
      ,s.schoolid
      ,s.status
      ,u.photo
      --,s.balance1
      ,u.title
      ,u.homeroom
      ,u.email_addr
      ,u.password
      ,u.numlogins
      --,u.ipaddrrestrict
      ,u.allowloginstart
      ,u.allowloginend
      ,u.psaccess
      --,u.accessvalue
      ,u.homepage
      ,u.loginid
      --,s.classpua
      ,s.noofcurclasses
      ,u.defaultstudscrn
      --,s.custom
      ,u.groupvalue
      ,u.teachernumber
      ,u.lunch_id
      --,s.balance2
      ,u.ssn
      ,u.home_phone
      ,u.school_phone
      ,u.street
      ,u.city
      ,u.state
      ,u.zip
      ,u.periodsavail
      ,u.powergradepw
      ,u.canchangeschool
      ,s.log
      ,u.teacherloginpw
      ,u.nameasimported
      ,u.teacherloginid
      ,u.teacherloginip
      ,u.supportcontact
      --,s.balance3
      --,s.balance4
      --,u.wm_status
      --,u.wm_statusdate
      ,u.wm_tier
      --,u.wm_address
      --,u.wm_password
      --,u.wm_createdate
      ,u.wm_createtime
      --,u.wm_ta_flag
      --,u.wm_ta_date
      ,u.wm_exclude
      ,s.staffstatus
      --,s.sched_gender
      ,s.sched_classroom
      --,s.sched_homeroom
      ,s.sched_department
      ,s.sched_maximumcourses
      ,s.sched_maximumduty
      ,s.sched_maximumfree
      ,s.sched_totalcourses
      ,s.sched_maximumconsecutive
      ,s.sched_isteacherfree
      --,s.sched_housecode
      --,s.sched_buildingcode
      --,s.sched_activitystatuscode
      --,s.sched_primaryschoolcode
      ,s.sched_teachermoreoneschool
      ,s.sched_substitute
      ,s.sched_scheduled
      --,u.wm_alias
      ,s.sched_usebuilding
      ,s.sched_usehouse
      ,u.ethnicity
      --,s.sched_team
      ,u.preferredname
      --,u.lastmeal
      ,s.sched_lunch
      ,u.staffpers_guid
      ,s.sched_maxpers
      ,s.sched_maxpreps
      ,u.adminldapenabled
      ,u.teacherldapenabled
      ,u.sif_stateprid
      ,u.maximum_load
      ,u.gradebooktype
      ,u.fedethnicity
      ,u.fedracedecline
      ,u.homeschoolid
      --,s.notes
      ,u.ptaccess
      ,s.users_dcid
FROM powerschool.users u
JOIN powerschool.schoolstaff s
  ON u.dcid = s.users_dcid