USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.u_def_ext_students AS

SELECT 'kippcamden' AS [db_name]
      ,[birth_certificate_proof]
      ,[default_family_web_id]
      ,[default_family_web_password]
      ,[default_student_web_id]
      ,[default_student_web_password]
      ,[iep_registration_followup]
      ,[lep_registration_followup]
      ,[lunchstatus_1314]
      ,[residency_proof_1]
      ,[residency_proof_2]
      ,[residency_proof_3]
      ,[reverification_date]
      ,[rti_tier_bhv]
      ,[rti_tier_eng]
      ,[rti_tier_math]
      ,[rti_tier_rhet]
      ,[rti_tier_sci]
      ,[rti_tier_soc]
      ,[rti_tier_wl]
      ,[spedcode_1314]
      ,[spedlep_1314]
      ,[studentsdcid]
      ,NULL AS [test_field]
FROM kippcamden.powerschool.u_def_ext_students
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[birth_certificate_proof]
      ,[default_family_web_id]
      ,[default_family_web_password]
      ,[default_student_web_id]
      ,[default_student_web_password]
      ,[iep_registration_followup]
      ,[lep_registration_followup]
      ,[lunchstatus_1314]
      ,[residency_proof_1]
      ,[residency_proof_2]
      ,[residency_proof_3]
      ,[reverification_date]
      ,[rti_tier_bhv]
      ,[rti_tier_eng]
      ,[rti_tier_math]
      ,[rti_tier_rhet]
      ,[rti_tier_sci]
      ,[rti_tier_soc]
      ,[rti_tier_wl]
      ,[spedcode_1314]
      ,[spedlep_1314]
      ,[studentsdcid]
      ,NULL AS [test_field]
FROM kippnewark.powerschool.u_def_ext_students;