USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.category_grades_static AS

SELECT 'kippcamden' AS [db_name]
      ,[student_number]
      ,[schoolid]
      ,[academic_year]
      ,[credittype]
      ,[course_number]
      ,[course_name]
      ,[sectionid]
      ,[teacher_name]
      ,[reporting_term]
      ,[grade_category]
      ,[grade_category_pct]
      ,[grade_category_pct_y1]
      ,[is_curterm]
      ,[rn_curterm]
FROM kippcamden.powerschool.category_grades_static
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[student_number]
      ,[schoolid]
      ,[academic_year]
      ,[credittype]
      ,[course_number]
      ,[course_name]
      ,[sectionid]
      ,[teacher_name]
      ,[reporting_term]
      ,[grade_category]
      ,[grade_category_pct]
      ,[grade_category_pct_y1]
      ,[is_curterm]
      ,[rn_curterm]
FROM kippmiami.powerschool.category_grades_static
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[student_number]
      ,[schoolid]
      ,[academic_year]
      ,[credittype]
      ,[course_number]
      ,[course_name]
      ,[sectionid]
      ,[teacher_name]
      ,[reporting_term]
      ,[grade_category]
      ,[grade_category_pct]
      ,[grade_category_pct_y1]
      ,[is_curterm]
      ,[rn_curterm]
FROM kippnewark.powerschool.category_grades_static;