USE [gabby];
GO

CREATE OR ALTER VIEW powerschool.storedgrades AS

SELECT 'kippcamden' AS [db_name]
      ,[absences]
      ,[academic_year]
      ,NULL AS [behavior]
      ,[comment_value]
      ,[course_name]
      ,[course_number]
      ,[course_number_clean]
      ,[credit_type]
      ,[datestored]
      ,[dcid]
      ,[earnedcrhrs]
      ,[excludefromclassrank]
      ,[excludefromgpa]
      ,[excludefromgradesuppression]
      ,[excludefromgraduation]
      ,[excludefromhonorroll]
      ,[excludefromtranscripts]
      ,[gpa_addedvalue]
      ,[gpa_custom_2]
      ,[gpa_points]
      ,[grade]
      ,[grade_level]
      ,[gradereplacementpolicy_id]
      ,[gradescale_name]
      ,[isearnedcrhrsfromgb]
      ,[ispotentialcrhrsfromgb]
      ,[log]
      ,[percent]
      ,[potentialcrhrs]
      ,[replaced_dcid]
      ,[replaced_equivalent_course]
      ,[schoolid]
      ,[schoolname]
      ,[sectionid]
      ,[storecode]
      ,[storecode_clean]
      ,[storecode_type]
      ,[studentid]
      ,[tardies]
      ,[teacher_name]
      ,[termbinsname]
      ,[termid]
      ,[_line]
FROM kippcamden.powerschool.storedgrades
UNION ALL
SELECT 'kippmiami' AS [db_name]
      ,[absences]
      ,[academic_year]
      ,NULL AS [behavior]
      ,[comment_value]
      ,[course_name]
      ,[course_number]
      ,[course_number_clean]
      ,[credit_type]
      ,[datestored]
      ,[dcid]
      ,[earnedcrhrs]
      ,[excludefromclassrank]
      ,[excludefromgpa]
      ,[excludefromgradesuppression]
      ,[excludefromgraduation]
      ,[excludefromhonorroll]
      ,[excludefromtranscripts]
      ,[gpa_addedvalue]
      ,[gpa_custom_2]
      ,[gpa_points]
      ,[grade]
      ,[grade_level]
      ,[gradereplacementpolicy_id]
      ,[gradescale_name]
      ,[isearnedcrhrsfromgb]
      ,[ispotentialcrhrsfromgb]
      ,[log]
      ,[percent]
      ,[potentialcrhrs]
      ,[replaced_dcid]
      ,[replaced_equivalent_course]
      ,[schoolid]
      ,[schoolname]
      ,[sectionid]
      ,[storecode]
      ,[storecode_clean]
      ,[storecode_type]
      ,[studentid]
      ,[tardies]
      ,[teacher_name]
      ,[termbinsname]
      ,[termid]
      ,[_line]
FROM kippmiami.powerschool.storedgrades
UNION ALL
SELECT 'kippnewark' AS [db_name]
      ,[absences]
      ,[academic_year]
      ,NULL AS [behavior]
      ,[comment_value]
      ,[course_name]
      ,[course_number]
      ,[course_number_clean]
      ,[credit_type]
      ,[datestored]
      ,[dcid]
      ,[earnedcrhrs]
      ,[excludefromclassrank]
      ,[excludefromgpa]
      ,[excludefromgradesuppression]
      ,[excludefromgraduation]
      ,[excludefromhonorroll]
      ,[excludefromtranscripts]
      ,[gpa_addedvalue]
      ,[gpa_custom_2]
      ,[gpa_points]
      ,[grade]
      ,[grade_level]
      ,[gradereplacementpolicy_id]
      ,[gradescale_name]
      ,[isearnedcrhrsfromgb]
      ,[ispotentialcrhrsfromgb]
      ,[log]
      ,[percent]
      ,[potentialcrhrs]
      ,[replaced_dcid]
      ,[replaced_equivalent_course]
      ,[schoolid]
      ,[schoolname]
      ,[sectionid]
      ,[storecode]
      ,[storecode_clean]
      ,[storecode_type]
      ,[studentid]
      ,[tardies]
      ,[teacher_name]
      ,[termbinsname]
      ,[termid]
      ,[_line]
FROM kippnewark.powerschool.storedgrades;