version: 2

sources:
  - name: adp
    tables:
      - name: employees_all
      - name: employees_archive
  - name: zendesk
    tables:
      - name: ticket_metrics
  - name: whetstone
    tables:
      - name: assignments
      - name: observations
  - name: illuminate_dna_assessments
    tables:
      - name: agg_student_responses
      - name: agg_student_responses_group
      - name: agg_student_responses_standard
      - name: assessment_grade_levels
      - name: assessment_standards
      - name: assessments_reporting_groups
      - name: fields
      - name: performance_bands
      - name: students_assessments
      - name: students_assessments_archive
  - name: illuminate_dna_repositories
    tables:
      - name: repository_grade_levels
  - name: illuminate_public
    tables:
      - name: student_session_aff
      - name: users
  - name: coupa
    tables:
      - name: users
      - name: budget_line_list
