name: Trunk Lint & Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: null

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1.0.4
        with:
          arguments: --fix
